### ISSUE TITLE
Ability to define "basePath"

### ISSUE THREAD

**Issue by vykozlov** [ai4os/DEEPaaS#111]
### Description

Sometimes, especially when behind the reverse proxy, it might be useful to have "basePath" for the API not as `/` but as something else, e.g `/api`. It would be nice, if a user could (re-)define this "basePath"

In the case of OAS3, in swagger.yaml this would correspond to:

```
servers:
  - url: /api
```

Ref: https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by alvarolopez** [comment]
This is not working, as only the UI is being mounted under the new path.
